Add style check for expect_after in tests
Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>

diff --git a/utils/check-style/check-style b/utils/check-style/check-style
--- a/utils/check-style/check-style
+++ b/utils/check-style/check-style
@@ -338,6 +338,13 @@ for test_case in "${expect_tests[@]}"; do
         pattern="^spawn.*CLICKHOUSE_CLIENT_BINARY.*--history_file$"
         grep -q "$pattern" "$test_case" || echo "Missing '$pattern' in '$test_case'"
     fi
+
+    # Otherwise expect_after/expect_before will not bail without stdin attached
+    # (and actually this is a hack anyway, correct way is to use $any_spawn_id)
+    pattern="-i \$any_spawn_id timeout"
+    grep -q -- "$pattern" "$test_case" || echo "Missing '$pattern' in '$test_case'"
+    pattern="-i \$any_spawn_id eof"
+    grep -q -- "$pattern" "$test_case" || echo "Missing '$pattern' in '$test_case'"
 done
 
 # Conflict markers
