CLICKHOUSE-4109 mlock clickhouse

diff --git a/debian/clickhouse-server.postinst b/debian/clickhouse-server.postinst
--- a/debian/clickhouse-server.postinst
+++ b/debian/clickhouse-server.postinst
@@ -90,6 +90,10 @@ Please fix this and reinstall this package." >&2
         && setcap cap_net_admin=+ep "${CLICKHOUSE_BINDIR}/${CLICKHOUSE_GENERIC_PROGRAM}" \
         || echo "Cannot set 'net_admin' capability for clickhouse binary. This is optional. Taskstats accounting will be disabled. To enable taskstats accounting you may add the required capability later manually."
 
+    command -v setcap >/dev/null \
+        && setcap cap_ipc_lock=+ep "${CLICKHOUSE_BINDIR}/${CLICKHOUSE_GENERIC_PROGRAM}" \
+        || echo "Cannot set 'ipc_lock' capability for clickhouse binary. This is optional. mlock of clickhouse binary will be disabled."
+
     # Clean old dynamic compilation results
     if [ -d "${CLICKHOUSE_DATADIR}/build" ]; then
         rm -f ${CLICKHOUSE_DATADIR}/build/*.cpp ${CLICKHOUSE_DATADIR}/build/*.so ||:
