dbms: modified test [#METR-2944].

diff --git a/dbms/tests/clickhouse-test b/dbms/tests/clickhouse-test
--- a/dbms/tests/clickhouse-test
+++ b/dbms/tests/clickhouse-test
@@ -19,7 +19,7 @@ MSG_UNKNOWN="${COLOR_WHITE}[ ${COLOR_UNKNOWN}UNKNOWN${COLOR_WHITE} ]${COLOR_RESE
 MSG_OK="${COLOR_WHITE}[ ${COLOR_OK}OK${COLOR_WHITE} ]${COLOR_RESET}"
 MSG_GENERATED="${COLOR_WHITE}[ ${COLOR_UNKNOWN}GENERATED${COLOR_WHITE} ]${COLOR_RESET}"
 
-HAS_ERROR=0
+ERRORS=0
 
 
 for query_file in $(ls $QUERIES_DIR/*.sql)
@@ -37,7 +37,7 @@ do
 	ret_code=$?
 
 	if [ $ret_code -ne 0 ]; then
-		HAS_ERROR=1
+		ERRORS=$(($ERRORS + 1))
 		echo -e "$MSG_FAIL - return code $ret_code"
 		if [ -s "$error_file" ]; then
 			cat $error_file
@@ -47,7 +47,7 @@ do
 			exit 1;
 		fi
 	elif [ -s "$error_file" ]; then
-		HAS_ERROR=1
+		ERRORS=$(($ERRORS + 1))
 		echo -e "$MSG_FAIL - having stderror:"
 		cat $error_file
 	elif [ ! -e "$reference_file" ]; then
@@ -61,7 +61,7 @@ do
 	else
 		diff $reference_file $result_file > $diff_file
 		if [ -s "$diff_file" ]; then
-			HAS_ERROR=1
+			ERRORS=$(($ERRORS + 1))
 			echo -e "$MSG_FAIL - result differs with reference:"
 			cat $diff_file
 		else
@@ -71,4 +71,13 @@ do
 	fi
 done
 
-exit $HAS_ERROR
+
+echo
+
+if [ $ERRORS -gt 0 ]; then
+	echo -e "${COLOR_FAIL}Having $ERRORS errors!${COLOR_RESET}"
+	exit 1
+else
+	echo -e "${COLOR_OK}All tests succeeded.${COLOR_RESET}"
+	exit 0
+fi
