dbms: updated tests [#METR-2944].

diff --git a/dbms/tests/clickhouse-test b/dbms/tests/clickhouse-test
--- a/dbms/tests/clickhouse-test
+++ b/dbms/tests/clickhouse-test
@@ -21,58 +21,71 @@ MSG_GENERATED="${COLOR_WHITE}[ ${COLOR_UNKNOWN}GENERATED${COLOR_WHITE} ]${COLOR_
 
 ERRORS=0
 
-
-for query_file in $(ls $QUERIES_DIR/*.sql)
+for dir in $(ls $QUERIES_DIR)
 do
-	test_name=$(basename $query_file .sql)
+	tests_name=$(echo $dir | sed -E 's/^[0-9_]+//')
 
-	result_file=$QUERIES_DIR/$test_name.result
-	error_file=$QUERIES_DIR/$test_name.error
-	reference_file=$QUERIES_DIR/$test_name.reference
-	diff_file=$QUERIES_DIR/$test_name.diff
+	echo
+	echo "Running $tests_name tests."
+	echo
 
-	printf "%-60s" "$test_name: "
-
-	$CLIENT_PROGRAM < $query_file > $result_file 2> $error_file
-	ret_code=$?
-
-	if [ $ret_code -ne 0 ]; then
-		ERRORS=$(($ERRORS + 1))
-		echo -e "$MSG_FAIL - return code $ret_code"
-		if [ -s "$error_file" ]; then
-			cat $error_file
-		fi
-		# разорвано соединение с сервером
-		if grep -q -E "Connection refused|Attempt to read after eof" $error_file; then
-			exit 1;
-		fi
-	elif [ -s "$error_file" ]; then
-		ERRORS=$(($ERRORS + 1))
-		echo -e "$MSG_FAIL - having stderror:"
-		cat $error_file
-	elif grep -q "Exception" $result_file; then
-		ERRORS=$(($ERRORS + 1))
-		echo -e "$MSG_FAIL - having exception:"
-		cat $result_file
-	elif [ ! -e "$reference_file" ]; then
-		# надо сгенерировать эталонный результат
-		if [ "$1" == "--generate" ]; then
-			cp $result_file $reference_file
-			echo -e "$MSG_GENERATED - no reference file"
-		else
-			echo -e "$MSG_UNKNOWN - no reference file (use --generate to create)"
-		fi
-	else
-		diff $reference_file $result_file > $diff_file
-		if [ -s "$diff_file" ]; then
-			ERRORS=$(($ERRORS + 1))
-			echo -e "$MSG_FAIL - result differs with reference:"
-			cat $diff_file
-		else
-			echo -e "$MSG_OK"
-			rm $error_file $result_file $diff_file
-		fi
+	if [[ "$tests_name" =~ "stateful" && 0 -eq $(echo "EXISTS TABLE test.hits" | $CLIENT_PROGRAM) ]]; then
+		echo "Won't run stateful tests because test data wasn't loaded. See README.txt."
+		continue
 	fi
+
+	for query_file in $(ls $QUERIES_DIR/$dir/*.sql)
+	do
+		test_name=$(basename $query_file .sql)
+
+		result_file=$QUERIES_DIR/$dir/$test_name.result
+		error_file=$QUERIES_DIR/$dir/$test_name.error
+		reference_file=$QUERIES_DIR/$dir/$test_name.reference
+		diff_file=$QUERIES_DIR/$dir/$test_name.diff
+
+		printf "%-60s" "$test_name: "
+
+		$CLIENT_PROGRAM < $query_file > $result_file 2> $error_file
+		ret_code=$?
+
+		if [ $ret_code -ne 0 ]; then
+			ERRORS=$(($ERRORS + 1))
+			echo -e "$MSG_FAIL - return code $ret_code"
+			if [ -s "$error_file" ]; then
+				cat $error_file
+			fi
+			# разорвано соединение с сервером
+			if grep -q -E "Connection refused|Attempt to read after eof" $error_file; then
+				exit 1;
+			fi
+		elif [ -s "$error_file" ]; then
+			ERRORS=$(($ERRORS + 1))
+			echo -e "$MSG_FAIL - having stderror:"
+			cat $error_file
+		elif grep -q "Exception" $result_file; then
+			ERRORS=$(($ERRORS + 1))
+			echo -e "$MSG_FAIL - having exception:"
+			cat $result_file
+		elif [ ! -e "$reference_file" ]; then
+			# надо сгенерировать эталонный результат
+			if [ "$1" == "--generate" ]; then
+				cp $result_file $reference_file
+				echo -e "$MSG_GENERATED - no reference file"
+			else
+				echo -e "$MSG_UNKNOWN - no reference file (use --generate to create)"
+			fi
+		else
+			diff $reference_file $result_file > $diff_file
+			if [ -s "$diff_file" ]; then
+				ERRORS=$(($ERRORS + 1))
+				echo -e "$MSG_FAIL - result differs with reference:"
+				cat $diff_file
+			else
+				echo -e "$MSG_OK"
+				rm $error_file $result_file $diff_file
+			fi
+		fi
+	done
 done
 
 
@@ -82,6 +95,6 @@ if [ $ERRORS -gt 0 ]; then
 	echo -e "${COLOR_FAIL}Having $ERRORS errors!${COLOR_RESET}"
 	exit 1
 else
-	echo -e "${COLOR_OK}All tests succeeded.${COLOR_RESET}"
+	echo -e "${COLOR_OK}All tests passed.${COLOR_RESET}"
 	exit 0
 fi
