New Create Release workflow

diff --git a/.github/workflows/create_release.yml b/.github/workflows/create_release.yml
--- a/.github/workflows/create_release.yml
+++ b/.github/workflows/create_release.yml
@@ -19,11 +19,80 @@ concurrency:
           - patch
 
 jobs:
-  Release:
+  PushTagAndCreateGhRelease:
+    outputs:
+      GITHUB_TAG: ${{ steps.TagAndRelease.outputs.GITHUB_TAG }}
     runs-on: [self-hosted, style-checker-aarch64]
     steps:
+      - name: Set envs
+        # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#multiline-strings
+        run: |
+          cat >> "$GITHUB_ENV" << 'EOF'
+          TEMP_PATH=${{runner.temp}}/cherry_pick
+          ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
+          ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
+          RCSK
+          REPO_OWNER=ClickHouse
+          REPO_NAME=ClickHouse
+          REPO_TEAM=core
+          EOF
       - name: Check out repository code
         uses: ClickHouse/checkout@v1
-      - name: Print greeting
+        with:
+          clear-repository: true
+          token: ${{secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN}}
+          fetch-depth: 0
+      - name: TagAndRelease
+        env:
+          GH_TOKEN: ${{ secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN }}
         run: |
-          python3 ./tests/ci/release.py --commit ${{ inputs.sha }} --type ${{ inputs.type }} --dry-run
+          echo "token=$GH_TOKEN"
+          echo "ROBOT_CLICKHOUSE_SSH_KEY=$ROBOT_CLICKHOUSE_SSH_KEY"
+          cd ./tests/ci
+          python3 ./release.py --commit ${{ inputs.sha }} --type ${{ inputs.type }} --dry-run --with-stderr --no-check-dirty --no-run-from-master
+          GITHUB_TAG=$(cat ./tag.tmp)
+          echo "GITHUB_TAG=$GITHUB_TAG" >> "$GITHUB_ENV"
+          echo "GITHUB_TAG=$GITHUB_TAG" >> "$GITHUB_OUTPUT"
+          echo "New release tag: $GITHUB_TAG"
+      - name: CheckTagReady
+        if: ${{ inputs.type == 'patch' }}
+        run: |
+            if ${{ inputs.type == 'patch' }}; then
+                [ -z "$GITHUB_TAG" ] && echo "ERROR: No release tag found" && exit 1
+            else
+                [ -n "$GITHUB_TAG" ] && echo "ERROR: Release tag must not be set in env for new release" && exit 1
+            fi
+            echo "Alles goed - continue"
+#      - name: Update versions, docker version, changelog, security
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN }}
+#        run: |
+#          ./utils/list-versions/list-versions.sh > ./utils/list-versions/version_date.tsv
+#          ./utils/list-versions/update-docker-version.sh
+#          GID=$(id -g "${UID}")
+#          # --network=host and CI=1 are required for the S3 access from a container
+#          docker run -u "${UID}:${GID}" -e PYTHONUNBUFFERED=1 -e CI=1 --network=host \
+#              --volume="${GITHUB_WORKSPACE}:/ClickHouse" clickhouse/style-test \
+#                  /ClickHouse/tests/ci/changelog.py -v --debug-helpers \
+#                  --gh-user-or-token="$GITHUB_TOKEN" --jobs=5 \
+#                  --output="/ClickHouse/docs/changelogs/${GITHUB_TAG}.md" "${GITHUB_TAG}"
+#          git add "./docs/changelogs/${GITHUB_TAG}.md"
+#          python3 ./utils/security-generator/generate_security.py > SECURITY.md
+#          git diff HEAD
+#      - name: Create Pull Request
+#        uses: peter-evans/create-pull-request@v6
+#        with:
+#          author: "robot-clickhouse <robot-clickhouse@users.noreply.github.com>"
+#          token: ${{ secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN }}
+#          committer: "robot-clickhouse <robot-clickhouse@users.noreply.github.com>"
+#          commit-message: Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}
+#          branch: auto/${{ env.GITHUB_TAG }}
+#          assignees: ${{ github.event.sender.login }}  # assign the PR to the tag pusher
+#          delete-branch: true
+#          title: Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}
+#          labels: do not test
+#          body: |
+#            Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}
+#
+#            ### Changelog category (leave one):
+#            - Not for changelog (changelog entry is not required)
