Disable server test

diff --git a/.github/workflows/jepsen.yml b/.github/workflows/jepsen.yml
--- a/.github/workflows/jepsen.yml
+++ b/.github/workflows/jepsen.yml
@@ -31,7 +31,6 @@ jobs:
           sudo rm -fr "$TEMP_PATH"
           mkdir -p "$TEMP_PATH"
           cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          docker build -f "$REPO_COPY/docker/test/keeper-jepsen/Dockerfile" -t clickhouse/keeper-jepsen-test "$REPO_COPY/docker/test/keeper-jepsen"
           cd "$REPO_COPY/tests/ci"
           python3 jepsen_check.py keeper
       - name: Cleanup
@@ -40,35 +39,34 @@ jobs:
           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
           sudo rm -fr "$TEMP_PATH"
-  ServerJepsenRelease:
-    runs-on: [self-hosted, style-checker]
-    if: ${{ always() }}
-    needs: [KeeperJepsenRelease]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/server_jepsen
-          REPO_COPY=${{runner.temp}}/server_jepsen/ClickHouse
-          EOF
-      - name: Clear repository
-        run: |
-          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
-      - name: Check out repository code
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Jepsen Test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          docker build -f "$REPO_COPY/docker/test/server-jepsen/Dockerfile" -t clickhouse/server-jepsen-test "$REPO_COPY/docker/test/server-jepsen"
-          cd "$REPO_COPY/tests/ci"
-          python3 jepsen_check.py server
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
+  #ServerJepsenRelease:
+  #  runs-on: [self-hosted, style-checker]
+  #  if: ${{ always() }}
+  #  needs: [KeeperJepsenRelease]
+  #  steps:
+  #    - name: Set envs
+  #      run: |
+  #        cat >> "$GITHUB_ENV" << 'EOF'
+  #        TEMP_PATH=${{runner.temp}}/server_jepsen
+  #        REPO_COPY=${{runner.temp}}/server_jepsen/ClickHouse
+  #        EOF
+  #    - name: Clear repository
+  #      run: |
+  #        sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
+  #    - name: Check out repository code
+  #      uses: actions/checkout@v2
+  #      with:
+  #        fetch-depth: 0
+  #    - name: Jepsen Test
+  #      run: |
+  #        sudo rm -fr "$TEMP_PATH"
+  #        mkdir -p "$TEMP_PATH"
+  #        cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #        cd "$REPO_COPY/tests/ci"
+  #        python3 jepsen_check.py server
+  #    - name: Cleanup
+  #      if: always()
+  #      run: |
+  #        docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #        docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #        sudo rm -fr "$TEMP_PATH"
